services:
  db:
    image: surrealdb/surrealdb:latest
    user: root
    command: start --user root --pass root file:///data
    ports:
      - "8082:8000"
    volumes:
      - surrealdb_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: db:8000
      PORT: 8000
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_NS: app
      DATABASE_NAME: todos
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - backend_target:/app/target
      - cargo_registry:/usr/local/cargo/registry

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - frontend_target:/app/frontend/target
      - cargo_registry:/usr/local/cargo/registry

volumes:
  surrealdb_data:
  backend_target:
  frontend_target:
  cargo_registry:
