services:
  db:
    image: surrealdb/surrealdb:latest
    command: start --user root --pass root
    ports:
      - "8080:8000"
    volumes:
      - surrealdb_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    environment:
      DATABASE_URL: db:8000
      PORT: 8000
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_NS: app
      DATABASE_NAME: todos
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  surrealdb_data:
