services:
  db:
    image: surrealdb/surrealdb:v2.0.4
    command: start --user ${DB_USER} --pass ${DB_PASS} file:///data
    expose:
      - "8000"
    volumes:
      - surrealdb_data:/data
    restart: always
    healthcheck:
      test: [ "CMD", "/surreal", "is-ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    environment:
      DATABASE_URL: db:8000
      PORT: 8000
      DATABASE_USER: ${DB_USER}
      DATABASE_PASS: ${DB_PASS}
      DATABASE_NS: ${DB_NS:-app}
      DATABASE_NAME: ${DB_NAME:-todos}
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  surrealdb_data:
